/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-10-05 06:47:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jsputil.cart.*;
import java.util.*;

public final class bread_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/inc/Common.jsp", Long.valueOf(1475646328000L));
    _jspx_dependants.put("/inc/Footer.jsp", Long.valueOf(1475538578000L));
    _jspx_dependants.put("/inc/Header2.jsp", Long.valueOf(1475541798000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("jsputil.cart");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	if (session.getAttribute("username") == null) {
		session.setAttribute("username", request.getParameter("username"));
	}

	String goodsCode = request.getParameter("goodsCode"); // 선택되어진 코드값 객체에 저장
	String username = (String) session.getAttribute("username"); // 세션 유저 정보 가져오기

	GoodsDAO goodsDao = new GoodsDAO(); // 어레이 리스트 사용할 객체 생성
	ArrayList<Goods> goodsList = goodsDao.getGoodsList();

	// GoodsDAO 클래스의 값 중에서 이전에 선택되어진 값만 goods객체에 가지고 있기
	Goods goods = new Goods();
	for (int i = 0; i < goodsList.size(); i++) {
		goods = goodsList.get(i);
		if (goods.getCode().equals(goodsCode)) { // 기존에 선택된 상품이면 빠져나가기
			break;
		}
	}

	// 선택한 상품 넣을 리스트 초기화 한번하기
	ArrayList<Goods> list = (ArrayList<Goods>) session.getAttribute("cartlist");
	if (list == null) { // 데이터가 없으면 객체 생성 / 데이터가 있으면 객체 생성안한다.
		list = new ArrayList<Goods>();
		session.setAttribute("cartlist", list);
	}

	// 선택한 상품이 중복이면 수량 증가시키기
	int cnt = 0;
	Goods goodsQnt = new Goods();
	for (int i = 0; i < list.size(); i++) {
		goodsQnt = list.get(i);
		if (goodsQnt.getCode().equals(goodsCode)) {
			cnt++;
			int orderQnt = goodsQnt.getOrderQnt() + 1;
			goodsQnt.setOrderQnt(orderQnt);
		}
	}
	if (cnt == 0) { // 선택한 상품이 중복이 아니닌 처음이면 처음한번만 리스트값 생성
		goods.setOrderQnt(1);
		list.add(goods);
	}

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\" />\r\n");
      out.write("<title>Royal</title>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery Framework 참조하기 -->\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("/** web18/10-titlebar.html 의 코드를 재활용 */\r\n");
      out.write("/** 기본 초기화 처리 */\r\n");
      out.write(".form-horizontal .form-group {\r\n");
      out.write("\tmargin-right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.row {\r\n");
      out.write("\tmargin-right: 0;\r\n");
      out.write("\tmin-height: 950px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/****************************** banner *********************/\r\n");
      out.write(".banner {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: #fff6cc\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**  타이틀 바 영역의 배경 색상 그라데이션 처리 */\r\n");
      out.write(".titlebar {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\tborder-bottom: 1px solid #555;\r\n");
      out.write("\t/** 웹킷에 대한 그라데이션 - 강의시간에는 구글 크롬만 대상으로 합니다. */\r\n");
      out.write("\tbackground-image: -webkit-linear-gradient(top, rgb(255, 246, 204) 8%,\r\n");
      out.write("\t\trgb(255, 246, 204) 74%);\r\n");
      out.write("\ttext-align: -webkit-match-parent;\r\n");
      out.write("}\r\n");
      out.write("/** 리스트 항목 가로 배치 */\r\n");
      out.write(".navi>li {\r\n");
      out.write("\twidth: 16.5%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** float 처리 마감제 */\r\n");
      out.write(".navi:after {\r\n");
      out.write("\tcolor: '';\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** 링크의 사이즈 처리 및 텍스트 꾸밈 */\r\n");
      out.write(".navi>li>a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tline-height: 45px;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\t-webkit-transition: all 0.2s ease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-unstyled {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** 링크 마우스 오버 */\r\n");
      out.write(".navi>li:hover>a {\r\n");
      out.write("\tcolor: #f60;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: -1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** 2depth 메뉴 컨테이너 */\r\n");
      out.write(".navi>li>ul {\r\n");
      out.write("\tbackground: rgb(255, 246, 204);\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\t/** 타이틀바 보다 작은 값 */\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("\t/** 숨김 처리 */\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 2depth메뉴 보이기 처리 */\r\n");
      out.write(".navi>li:hover>ul {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("\tvisibility: visible;\r\n");
      out.write("\t-webkit-transition: all 0.5s;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 2depth 메뉴 컨테이너 각 항목 > 링크 */\r\n");
      out.write(".navi ul>li>a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 2depth 메뉴 컨테이너 각 항목 > 링크 마우스 오버 */\r\n");
      out.write(".navi ul>li>a:hover {\r\n");
      out.write("\tcolor: orange;\r\n");
      out.write("\tbackground: rgb(255, 246, 204);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*****************************  content*************************** */\r\n");
      out.write("#slide1 h1 {\r\n");
      out.write("\tmin-height: 750px;\r\n");
      out.write("\ttext-indent: -10000px;\r\n");
      out.write("\tpadding-right: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#slide2 {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#slide2 h3 {\r\n");
      out.write("\tmin-height: 750px;\r\n");
      out.write("\ttext-indent: -10000px;\r\n");
      out.write("\tpadding-right: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("\tmin-height: 800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box1 {\r\n");
      out.write("\tmargin-top: 50px;\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box2 {\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/******************** client join and update*************************** */\r\n");
      out.write("div.clientjoin {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmin-height: 750px;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tmargin-right: 130px;\r\n");
      out.write("\tmargin-left: 130px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.container {\r\n");
      out.write("\theight: 700px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tpadding-right: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".join {\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\talign: center;\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\talign: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-header {\r\n");
      out.write("\tmargin-top: 130px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/********************** FAQ******************************/\r\n");
      out.write(".tab_menu1 {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\twitdh: 250px;\r\n");
      out.write("\tmargin: 0 auto 20px;\r\n");
      out.write("\tmargin-top: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_menu1 li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 49.85%;\r\n");
      out.write("\tmargin-left: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_menu1 li:first-child {\r\n");
      out.write("\tmargin-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_menu1 li a {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mgb_20 {\r\n");
      out.write("\tmargin-bottom: 20px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_menu1.tab3>li {\r\n");
      out.write("\twidth: 33.2% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/***************************** inquire *************************************/\r\n");
      out.write(".Tarea {\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".area {\r\n");
      out.write("\twidth: 70%;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/************************************** Idsearch *************************************/\r\n");
      out.write(".Idsearch {\r\n");
      out.write("\tmin-height: 750px;\r\n");
      out.write("\tpadding-top: 100px;\r\n");
      out.write("\tmargin-left: 300px;\r\n");
      out.write("\tmargin-right: 300px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-top: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/***************************** LoginPage *************************************/\r\n");
      out.write(".loginB {\r\n");
      out.write("\tpadding-top: 100px;\r\n");
      out.write("\tmargin-left: 300px;\r\n");
      out.write("\tmargin-right: 300px;\r\n");
      out.write("\tmin-height: 800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Lbutton {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".joinB {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("\twidth: 60%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/************************************** myorderlist  *************************************/\r\n");
      out.write(".page-name { /** 장바구니 */\r\n");
      out.write("\tcolor: rgb(29, 135, 115);\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tmargin-top: 130px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inner-content {\r\n");
      out.write("\tpadding-top: 15px;\r\n");
      out.write("\tpadding-bottom: 0px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tborder: 1px solid #eee;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/************************************** mypage  *************************************/\r\n");
      out.write(".page-name {\r\n");
      out.write("\tcolor: rgb(29, 135, 115);\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mybox h6 { /**박스 안 글자가 너무 붙은거 같아서 떨어뜨렸음.*/\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".myinner-content {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tborder: solid 2px #eee;\r\n");
      out.write("\tborder-bottom: 0px;\r\n");
      out.write("\theight: 350px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".myinner-content-container {\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tborder: solid 0px #eee;\r\n");
      out.write("\tborder-top: 0px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".myinner-content-info h5 {\r\n");
      out.write("\tpadding-bottom: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mybox {\r\n");
      out.write("\tborder: 1px solid #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".myinner-content .myinner-content-container .mybox {\r\n");
      out.write("\t/** 메뉴박스4개 링크영역 확장+마우스호버*/\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\theight: 160px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder: 1px solid #eee;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tmargin: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/************************************** mypayment  *************************************/\r\n");
      out.write(".payinner-content {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tborder: solid 2px #eee;\r\n");
      out.write("\tborder-bottom: 0px;\r\n");
      out.write("\theight: 350px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".payinner-content-container {\r\n");
      out.write("\theight: 155px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tborder: solid 0px #eee;\r\n");
      out.write("\tborder-top: 0px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".payinner-content-info h5 {\r\n");
      out.write("\tpadding-bottom: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".payinner-content .payinner-content-container .mybox {\r\n");
      out.write("\t/** 메뉴에 구현한 예약확인,구매확인 선택 박스 \r\n");
      out.write("\t\t디스플레이 인라인-블럭으로 링크영역 확장 후\r\n");
      out.write("\t\t커서 포인트로 링크영역 마우스 호버시 손가락 모양으로 바뀌게 하였다.\r\n");
      out.write("\t*/\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tborder: 1px solid #eee;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\theight: 160px;\r\n");
      out.write("\tmargin: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/************************************** mysquestionlist *************************************/\r\n");
      out.write(".myquestion-container {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".qeinner-content {\r\n");
      out.write("\tpadding-top: 15px;\r\n");
      out.write("\tpadding-bottom: 0px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tborder: solid 2px #eee;\r\n");
      out.write("\tborder-bottom: 1px solid #eee;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".qeinner-content-container {\r\n");
      out.write("\theight: 155px;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tborder: solid 0px #eee;\r\n");
      out.write("\tborder-top: 0px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".myquestionlist {\r\n");
      out.write("\tborder-bottom: 1px solid #eee;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".qeinner-content-info-text {\r\n");
      out.write("\tpadding-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button_my_question {\r\n");
      out.write("\t/* 페이지 하단에 있는 문의하기 삭제하기 버튼*/\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/************************************** orderList *************************************/\r\n");
      out.write("div.content {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmin-height: 750px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/** table */\r\n");
      out.write(".table-responsive {\r\n");
      out.write("\tpadding-top: 100px;\r\n");
      out.write("\tpadding-left: 130px;\r\n");
      out.write("\tpadding-right: 130px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-striped>tbody>tr:nth-child(odd)>td, .table-striped>tbody>tr:nth-child(odd)>th\r\n");
      out.write("\t{\r\n");
      out.write("\tbackground-color: white !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-striped>tbody>tr:hover>td, .table-striped>tbody>tr:hover>th {\r\n");
      out.write("\tbackground-color: orange !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/************************************** footer  *************************************/\r\n");
      out.write(".footer {\r\n");
      out.write("\tpadding-bottom: 0;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\t/* Set the fixed height of the footer here */\r\n");
      out.write("\tbackground-color: #f5f5f5;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".family_site {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footerWrap {\r\n");
      out.write("\tpadding-bottom: 0;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tbackground-color: #5f5353;\r\n");
      out.write("}\r\n");
      out.write("</style>");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".view {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tborder: 10px solid #fff;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbox-shadow: 1px 1px 2px #e6e6e6;\r\n");
      out.write("\tcursor: default;\r\n");
      out.write("\tbackground: #fff src(img/ 1.jpg) no-repeat center center\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view .mask, .view .content {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view img {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tposition: relative\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view h2 {\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, 0.8);\r\n");
      out.write("\tmargin: 20px 0 0 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view p {\r\n");
      out.write("\tfont-family: Georgia, serif;\r\n");
      out.write("\tfont-style: italic;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tpadding: 10px 20px 20px;\r\n");
      out.write("\ttext-align: center\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view a.info {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tpadding: 7px 14px;\r\n");
      out.write("\tbackground: #000;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\ttext-transform: uppercase;\r\n");
      out.write("\tbox-shadow: 0 0 1px #000\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view a.info:hover {\r\n");
      out.write("\tbox-shadow: 0 0 5px #000\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-first img {\r\n");
      out.write("\ttransition: all 0.2s linear;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-first .mask {\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\tbackground-color: rgba(219, 127, 8, 0.7);\r\n");
      out.write("\ttransition: all 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-first h2 {\r\n");
      out.write("\ttransform: translateY(-100px);\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\ttransition: all 0.2s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-first p {\r\n");
      out.write("\ttransform: translateY(100px);\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\ttransition: all 0.2s linear;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-first a.info {\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\ttransition: all 0.2s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-first:hover img {\r\n");
      out.write("\ttransform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-first:hover .mask {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-first:hover h2, .view-first:hover p, .view-first:hover a.info {\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("\ttransform: translateY(0px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-first:hover p {\r\n");
      out.write("\ttransition-delay: 0.1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-first:hover a.info {\r\n");
      out.write("\ttransition-delay: 0.2s;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("<!doctype html>\r\n");
      out.write("<div class=\"head\">\r\n");
      out.write("\t<div class=\"banner\">\r\n");
      out.write("\t\t<a href=\"\"> <img src=\"img/logo.png\" alt=\"logo\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"titlebar\">\r\n");
      out.write("\t\t<ul class=\"list-unstyled navi\">\r\n");
      out.write("\t\t\t<li><a href=\"./LoginPage.jsp\">LogOut</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"./MyPage.jsp\">MyPage</a>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./InformationUpdate.jsp\">Update</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./mypayment.jsp\">Payment</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./MybookingList.jsp\">Booking</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./MyquestionList.jsp\">Notice</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href=\"./Story.jsp\">Brand</a>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./Story.jsp\">Story</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Product</a>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./bread.jsp\">bread</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./cake.jsp\">cake</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./cookie.jsp\">cookie</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href=\"./CustomOrder.jsp\">Order</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Community</a>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"./FAQ.jsp\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">문의하기</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("<div class=\"page-header\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!---------------------------------------  장바구니   ----------------------------------- -->\r\n");
      out.write("\t\t<form class=\"form-horizontal\" id=\"inquireform\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-2\" style=\"padding-right: 0px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table class=\"table table-striped table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"text-center\" colspan=\"2\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: rgb(217, 204, 255)\">장바구니</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"text-center\">");
      out.print(goods.getCode());

 	// 상품 코드
 
      out.print(goods.getName());

 	// 상품 이름
 
      out.print(goods.getPrice());

 	// 상품 가격
 
      out.write(' ');
      out.write('(');
      out.print(goods.getOrderQnt());
      out.write(')');
      out.write(' ');

 	// 상품 수량
 
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"text-center\">삭제</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"text-center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: rgb(209, 255, 204)\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"text-center\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: rgb(209, 255, 204)\">총금액</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"text-center\" colspan=\"2\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: rgb(209, 255, 204)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\" onclick=' '>예약하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!--------------------------------------  장바구니 ------------ ------------------------- -->\r\n");
      out.write("\t\t<!-- 페이지 내용 영역 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t<ul id=\"myTab\" class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t<li class=\"active col-md-4\"><a href=\"bread.jsp\">bread</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"col-md-4\"><a href=\"cake.jsp\">cake</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"col-md-4\"><a href=\"cookie.jsp\">cookie</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!--// 탭 메뉴 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 탭 화면 시작 -->\r\n");
      out.write("\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tab-pane fade in active\" id=\"bread\">\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-first\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/bread/b001.jpg\" style=\"width: 300px; height: 200px;\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>빵에대한 설명 zxcfq wef sddd ddddd dddddd dddd dsdasfav zxx</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>1000won</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\" 현재 재고량 : 15 개\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 갯수 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"number\" name=\"quantity\" class=\"pull-left\" min=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmax=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button onclick=\"cartAdd('");
      out.print(goods.getCode());
      out.write("')\">추가</button>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-first\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/bread/b002.jpg\" style=\"width: 300px; height: 200px;\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>빵에대한 설명 zxcfq wef sddd ddddd dddddd dddd dsdasfav zxx</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>1000won</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\" 현재 재고량 : 15 개\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 갯수 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"number\" name=\"quantity\" class=\"pull-left\" min=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmax=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button onclick=\"cartAdd('");
      out.print(goods.getCode());
      out.write("')\">추가</button>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-first\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/bread/b003.jpg\" style=\"width: 300px; height: 200px;\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>빵에대한 설명 zxcfq wef sddd ddddd dddddd dddd dsdasfav zxx</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>1000won</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\" 현재 재고량 : 15 개\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 갯수 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"number\" name=\"quantity\" class=\"pull-left\" min=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmax=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button onclick=\"cartAdd('");
      out.print(goods.getCode());
      out.write("')\">추가</button>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-first\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/bread/b003.jpg\" style=\"width: 300px; height: 200px;\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>빵에대한 설명 zxcfq wef sddd ddddd dddddd dddd dsdasfav zxx</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>1000won</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\" 현재 재고량 : 15 개\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 갯수 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"number\" name=\"quantity\" class=\"pull-left\" min=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmax=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button onclick=\"cartAdd('");
      out.print(goods.getCode());
      out.write("')\">추가</button>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-first\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/bread/b004.jpg\" style=\"width: 300px; height: 200px;\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>빵에대한 설명 zxcfq wef sddd ddddd dddddd dddd dsdasfav zxx</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>1000won</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\" 현재 재고량 : 15 개\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 갯수 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"number\" name=\"quantity\" class=\"pull-left\" min=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmax=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button onclick=\"cartAdd('");
      out.print(goods.getCode());
      out.write("')\">추가</button>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-first\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/bread/b005.jpg\" style=\"width: 300px; height: 200px;\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>빵에대한 설명 zxcfq wef sddd ddddd dddddd dddd dsdasfav zxx</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>1000won</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\" 현재 재고량 : 15 개\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 갯수 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"number\" name=\"quantity\" class=\"pull-left\" min=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmax=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button onclick=\"cartAdd('");
      out.print(goods.getCode());
      out.write("')\">추가</button>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"view view-first\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"img/bread/b006.jpg\" style=\"width: 300px; height: 200px;\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>빵에대한 설명 zxcfq wef sddd ddddd dddddd dddd dsdasfav zxx</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>1000won</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\" 현재 재고량 : 15 개\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 갯수 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"number\" name=\"quantity\" class=\"pull-left\" min=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmax=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button onclick=\"cartAdd('");
      out.print(goods.getCode());
      out.write("')\">추가</button>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--// 탭 화면 끝 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"col-md-2\" id=\"slide1\">\r\n");
      out.write("\t\t<h1>슬라이드1</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("<!doctype html>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"footerWrap\">\r\n");
      out.write("\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<address>copyright 2016</address>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
